Repository Indipage/SERVER, pull requests merged in 2023-07, with the labels that each got.

#6 [CHORE] 무중단배포를 위한 nginx 관련 세팅을 완료한다.
  src/main/java/indipage/org/indipage/common/controller/ServerProfileController.java
  src/main/resources/application.yaml
Labels: CHORE, 🐭 승희

#2 [CHORE] CI/CD 관련 세팅
  .github/workflows/cd.yml
  .github/workflows/gradle.yml
  appspec.yml
  scripts/deploy.sh
  src/main/resources/application.yaml
Labels: CHORE, 🐭 승희

#15 [FEAT] 공간 상세보기시 태그 정보 조회 추가 #13
  src/main/java/indipage/org/indipage/api/space/controller/dto/response/SpaceDto.java
  src/main/java/indipage/org/indipage/api/space/service/SpaceService.java
  src/main/java/indipage/org/indipage/api/tag/controller/dto/response/TagDto.java
Labels: FEAT, 👾 준서

#16 [FEAT] 유저 정보 조회 기능 구현 #14
  src/main/java/indipage/org/indipage/api/user/controller/UserController.java
  src/main/java/indipage/org/indipage/api/user/controller/dto/response/UserDto.java
  src/main/java/indipage/org/indipage/api/user/service/UserService.java
  src/main/java/indipage/org/indipage/domain/UserRepository.java
  src/main/java/indipage/org/indipage/exception/Error.java
  src/main/java/indipage/org/indipage/exception/Success.java
Labels: FEAT, 🐭 승희

#18 [FEAT] 아티클 상세조회 기능 구현 #17
  src/main/java/indipage/org/indipage/api/article/controller/ArticleController.java
  src/main/java/indipage/org/indipage/api/article/controller/dto/response/ArticleResponseDto.java
  src/main/java/indipage/org/indipage/api/article/service/ArticleService.java
  src/main/java/indipage/org/indipage/domain/ArticleRepository.java
  src/main/java/indipage/org/indipage/exception/Error.java
  src/main/java/indipage/org/indipage/exception/Success.java
Labels: FEAT, 🐭 승희

#20 [FEAT] 추천 서가 조회 API를 구현한다.
  src/main/java/indipage/org/indipage/api/book/controller/dto/request/BookRequestDto.java
  src/main/java/indipage/org/indipage/api/book/controller/dto/response/BookDto.java
  src/main/java/indipage/org/indipage/api/space/controller/SpaceController.java
  src/main/java/indipage/org/indipage/api/space/controller/dto/response/BookRecommendationResponseDto.java
  src/main/java/indipage/org/indipage/api/space/service/SpaceService.java
  src/main/java/indipage/org/indipage/exception/Success.java
Labels: FEAT, 👾 준서

#27 [FEAT] 조르기 등록 기능 구현 #24
  src/main/java/indipage/org/indipage/api/space/controller/SpaceController.java
  src/main/java/indipage/org/indipage/api/space/service/SpaceService.java
  src/main/java/indipage/org/indipage/domain/FollowSpaceRelationRepository.java
  src/main/java/indipage/org/indipage/domain/Relation/FollowSpaceRelation.java
  src/main/java/indipage/org/indipage/exception/Success.java
Labels: FEAT, 🐭 승희

#30 [ADD] 아티클 상세 조회 시 썸네일을 포함하도록 수정 #28
  src/main/java/indipage/org/indipage/api/article/controller/dto/response/ArticleResponseDto.java
  src/main/java/indipage/org/indipage/api/article/service/ArticleService.java
  src/main/java/indipage/org/indipage/domain/Article.java
Labels: 🐭 승희, ADD

#35 [FEAT] 아티클 목록 전체 조회 기능 구현 #31
  src/main/java/indipage/org/indipage/api/article/controller/ArticleController.java
  src/main/java/indipage/org/indipage/api/article/controller/dto/response/ArticleSummaryResponseDto.java
  src/main/java/indipage/org/indipage/api/article/service/ArticleService.java
  src/main/java/indipage/org/indipage/api/space/service/SpaceService.java
  src/main/java/indipage/org/indipage/api/ticket/service/TicketService.java
  src/main/java/indipage/org/indipage/api/user/service/UserService.java
  src/main/java/indipage/org/indipage/domain/ArticleRepository.java
  src/main/java/indipage/org/indipage/exception/Success.java
Labels: FEAT, 🐭 승희

#32 [FEAT] 티켓 수령하기 API 구현
  src/main/java/indipage/org/indipage/api/user/controller/UserController.java
  src/main/java/indipage/org/indipage/api/user/service/UserService.java
  src/main/java/indipage/org/indipage/domain/InviteSpaceRelationRepository.java
  src/main/java/indipage/org/indipage/domain/Relation/InviteSpaceRelation.java
  src/main/java/indipage/org/indipage/domain/Relation/InviteSpaceRelationId.java
  src/main/java/indipage/org/indipage/exception/Error.java
  src/main/java/indipage/org/indipage/exception/Success.java
Labels: FEAT, 👾 준서

#37 [FEAT] 아티클 북마크 여부 조회 API 구현
  src/main/java/indipage/org/indipage/api/user/controller/UserController.java
  src/main/java/indipage/org/indipage/api/user/controller/dto/response/IsBookmarkedResponseDto.java
  src/main/java/indipage/org/indipage/api/user/service/UserService.java
  src/main/java/indipage/org/indipage/domain/ArticleBookmarkRelationRepository.java
  src/main/java/indipage/org/indipage/domain/Relation/ArticleBookmarkRelationId.java
  src/main/java/indipage/org/indipage/exception/Success.java
Labels: FEAT, 👾 준서

#44 [FIX] 공간 방문 api 라우터를 수정한다.
  src/main/java/indipage/org/indipage/api/space/controller/SpaceController.java
  src/main/java/indipage/org/indipage/api/space/service/SpaceService.java
  src/main/java/indipage/org/indipage/api/user/service/UserService.java
Labels: FIX, 👾 준서

#50 [FEAT] 아티클에 발행일 컬럼을 추가한다.
  src/main/java/indipage/org/indipage/api/article/controller/dto/response/ArticleResponseDto.java
  src/main/java/indipage/org/indipage/api/article/controller/dto/response/ArticleSummaryResponseDto.java
  src/main/java/indipage/org/indipage/domain/Article.java
Labels: FEAT, 🐭 승희, ADD

#65 [FEAT] 유저가 수령한 티켓 리스트 조회 api를 구현한다.
  src/main/java/indipage/org/indipage/api/space/controller/SpaceController.java
  src/main/java/indipage/org/indipage/api/space/controller/dto/response/ArticleOfSpaceResponseDto.java
  src/main/java/indipage/org/indipage/api/space/service/SpaceService.java
  src/main/java/indipage/org/indipage/api/ticket/controller/dto/response/ReceivedTicketResponseDto.java
  src/main/java/indipage/org/indipage/api/user/controller/UserController.java
  src/main/java/indipage/org/indipage/api/user/service/UserService.java
  src/main/java/indipage/org/indipage/domain/InviteSpaceRelationRepository.java
  src/main/java/indipage/org/indipage/exception/Success.java
Labels: FEAT, 👾 준서

#68 [CHORE] 공간의 아티클 조회 결과에 발행 여부 삭제 #61
  src/main/java/indipage/org/indipage/api/space/controller/dto/response/ArticleOfSpaceResponseDto.java
Labels: CHORE, 👾 준서

#60 [FEAT] 유저의 공간 북마크 리스트 조회 api를 구현한다.
  src/main/java/indipage/org/indipage/api/space/controller/dto/response/SpaceDto.java
  src/main/java/indipage/org/indipage/api/user/controller/UserController.java
  src/main/java/indipage/org/indipage/api/user/service/UserService.java
  src/main/java/indipage/org/indipage/domain/SpaceBookmarkRelationRepository.java
  src/main/java/indipage/org/indipage/exception/Success.java
Labels: FEAT, 👾 준서

#62 [FEAT] 위클리 아티클 조회 기능을 구현한다.
  src/main/java/indipage/org/indipage/api/article/controller/ArticleController.java
  src/main/java/indipage/org/indipage/api/article/controller/dto/response/WeeklyArticleResponseDto.java
  src/main/java/indipage/org/indipage/api/article/service/ArticleService.java
  src/main/java/indipage/org/indipage/domain/ArticleRepository.java
  src/main/java/indipage/org/indipage/domain/User.java
  src/main/java/indipage/org/indipage/exception/Error.java
  src/main/java/indipage/org/indipage/exception/Success.java
Labels: FEAT, 🐭 승희

#66 [FEAT] 유저가 아티클을 슬라이드한 날짜를 변경하는 기능을 구현한다.
  src/main/java/indipage/org/indipage/api/user/controller/UserController.java
  src/main/java/indipage/org/indipage/api/user/service/UserService.java
  src/main/java/indipage/org/indipage/domain/User.java
  src/main/java/indipage/org/indipage/exception/Success.java
Labels: FEAT, 🐭 승희

#69 [FIX] 발행일이 지나지 않은 아티클이 조회된다.
  src/main/java/indipage/org/indipage/api/article/service/ArticleService.java
  src/main/java/indipage/org/indipage/api/space/controller/SpaceController.java
  src/main/java/indipage/org/indipage/api/space/service/SpaceService.java
  src/main/java/indipage/org/indipage/domain/ArticleRepository.java
Labels: FIX, 🐭 승희

#73 [FEAT] 유저의 위클리 아티클 슬라이드 여부를 조회하는 api를 구현한다.
  src/main/java/indipage/org/indipage/api/article/controller/dto/response/HasSlideWeeklyArticleResponseDto.java
  src/main/java/indipage/org/indipage/api/user/controller/UserController.java
  src/main/java/indipage/org/indipage/api/user/service/UserService.java
  src/main/java/indipage/org/indipage/exception/Success.java
Labels: FEAT, 🐭 승희

#80 [FEAT] 검색 기능을 구현
  src/main/java/indipage/org/indipage/api/space/controller/SpaceController.java
  src/main/java/indipage/org/indipage/api/space/controller/dto/response/SpaceSearchResponseDto.java
  src/main/java/indipage/org/indipage/api/space/controller/dto/response/SpaceSearchWithCategoryResponseDto.java
  src/main/java/indipage/org/indipage/api/space/service/SpaceService.java
  src/main/java/indipage/org/indipage/domain/Address.java
  src/main/java/indipage/org/indipage/domain/ArticleRepository.java
  src/main/java/indipage/org/indipage/domain/BookRepository.java
  src/main/java/indipage/org/indipage/domain/Space.java
  src/main/java/indipage/org/indipage/domain/SpaceRepository.java
  src/main/java/indipage/org/indipage/exception/Success.java
Labels: FEAT, 🐭 승희

#82 [FIX] 검색 응답 시에 공간에 대한 이미지가 반환되지 않는다. #81
  src/main/java/indipage/org/indipage/api/space/controller/dto/response/SpaceSearchResponseDto.java
Labels: FIX, 🐭 승희

#84 [ADD] 뷰 수정에 따라 주소의 카테고리명을 사용하지 않는 검색 응답형태 추가 #83
  src/main/java/indipage/org/indipage/api/space/controller/SpaceController.java
  src/main/java/indipage/org/indipage/api/space/service/SpaceService.java
Labels: 🐭 승희, ADD

#89 [REFACTOR] createdAt 이 사용되지 않는 경우 삭제하고 LocalDateTime 을 형태를 맞춰 반환한다.
  src/main/java/indipage/org/indipage/api/article/controller/dto/response/ArticleResponseDto.java
  src/main/java/indipage/org/indipage/api/article/controller/dto/response/ArticleSummaryResponseDto.java
  src/main/java/indipage/org/indipage/api/ticket/controller/dto/response/ReceivedCardResponseDto.java
  src/main/java/indipage/org/indipage/api/user/controller/dto/response/UserDto.java
  src/main/java/indipage/org/indipage/api/user/service/UserService.java
Labels: REFACTOR, 🐭 승희

#92 [ADD] QR 인식 응답형태에 카드 이미지 url 추가 #91
  src/main/java/indipage/org/indipage/api/space/controller/SpaceController.java
  src/main/java/indipage/org/indipage/api/space/controller/dto/response/SpaceVisitResponseDto.java
  src/main/java/indipage/org/indipage/api/space/service/SpaceService.java
Labels: FIX, 🐭 승희

#93 [FIX] 정렬 누락된 부분 수정 #90
  src/main/java/indipage/org/indipage/api/article/service/ArticleService.java
  src/main/java/indipage/org/indipage/api/bookmark/controller/BookmarkController.java
  src/main/java/indipage/org/indipage/api/bookmark/service/BookmarkService.java
  src/main/java/indipage/org/indipage/api/user/controller/UserController.java
  src/main/java/indipage/org/indipage/api/user/service/UserService.java
  src/main/java/indipage/org/indipage/domain/ArticleBookmarkRelationRepository.java
  src/main/java/indipage/org/indipage/domain/ArticleRepository.java
  src/main/java/indipage/org/indipage/domain/SpaceBookmarkRelationRepository.java
Labels: FIX, 🐭 승희
