Repository Indipage/SERVER, pull requests merged in 2023-08, with the labels that each got.

#105 [ADD] 소셜 로그인 구현 시 공통으로 사용되는 클래스들을 추가한다.
  src/main/java/indipage/org/indipage/auth/Platform.java
  src/main/java/indipage/org/indipage/auth/dto/OAuthUserResponseDto.java
  src/main/java/indipage/org/indipage/auth/service/AppleOauthClient.java
  src/main/java/indipage/org/indipage/auth/service/OAuthClient.java
  src/main/java/indipage/org/indipage/auth/service/OAuthClientProvider.java
  src/main/java/indipage/org/indipage/domain/User.java
Labels: 🐭 승희, ADD

#107 [FEAT] 유저 인증 과정에서 사용할 JWT 로직을 구현한다. #106
  build.gradle
  src/main/java/indipage/org/indipage/auth/JwtProvider.java
  src/main/java/indipage/org/indipage/config/resolver/UserId.java
  src/main/java/indipage/org/indipage/config/resolver/UserIdResolver.java
  src/main/java/indipage/org/indipage/exception/Error.java
  src/main/resources/application.yaml
Labels: FEAT

#110 [FEAT] 애플로그인을 구현한다.
  build.gradle
  src/main/java/indipage/org/indipage/IndipageApplication.java
  src/main/java/indipage/org/indipage/api/auth/controller/AuthController.java
  src/main/java/indipage/org/indipage/auth/JwtProvider.java
  src/main/java/indipage/org/indipage/auth/dto/OAuthUserResponseDto.java
  src/main/java/indipage/org/indipage/auth/service/AppleOauthClient.java
  src/main/java/indipage/org/indipage/auth/service/AuthService.java
  src/main/java/indipage/org/indipage/auth/service/OAuthClient.java
  src/main/java/indipage/org/indipage/auth/service/OAuthClientProvider.java
  src/main/java/indipage/org/indipage/auth/service/apple/AppleIdentityTokenProcessor.java
  src/main/java/indipage/org/indipage/auth/service/apple/AppleOAuthClient.java
  src/main/java/indipage/org/indipage/auth/service/apple/ApplePublicKeyGenerator.java
  src/main/java/indipage/org/indipage/auth/service/apple/ApplePublicKeys.java
  src/main/java/indipage/org/indipage/auth/utils/EncryptUtils.java
  src/main/java/indipage/org/indipage/exception/Error.java
Labels: FEAT, 🐭 승희

#112 [FIX] 애플 로그인 과정에서 누락된 설정을 추가한다.
  src/main/java/indipage/org/indipage/domain/User.java
  src/main/resources/application.yaml
Labels: FIX
