Repository Indipage/SERVER, pull requests merged in 2023-09, with the labels that each got.

#114 [FEAT] 구글 소셜 로그인을 구현한다.
  src/main/java/indipage/org/indipage/auth/service/JWKs.java
  src/main/java/indipage/org/indipage/auth/service/PublicKeyGenerator.java
  src/main/java/indipage/org/indipage/auth/service/apple/AppleOAuthClient.java
  src/main/java/indipage/org/indipage/auth/service/google/GoogleIdTokenProcessor.java
  src/main/java/indipage/org/indipage/auth/service/google/GoogleOAuthClient.java
  src/main/resources/application.yaml
Labels: FEAT

#117 [REFACTOR] 애플과 구글 로그인에 중복되는 TokenProcessor를 분리한다.
  src/main/java/indipage/org/indipage/IndipageApplication.java
  src/main/java/indipage/org/indipage/api/image/controller/ImageController.java
  src/main/java/indipage/org/indipage/auth/service/IdentityTokenProcessor.java
  src/main/java/indipage/org/indipage/auth/service/OAuthClientProvider.java
  src/main/java/indipage/org/indipage/auth/service/apple/AppleIdentityTokenProcessor.java
  src/main/java/indipage/org/indipage/auth/service/apple/AppleOAuthClient.java
  src/main/java/indipage/org/indipage/auth/service/apple/AppleTokenValidationContext.java
  src/main/java/indipage/org/indipage/auth/service/google/GoogleIdTokenProcessor.java
  src/main/java/indipage/org/indipage/auth/service/google/GoogleOAuthClient.java
  src/main/java/indipage/org/indipage/auth/service/google/GoogleTokenValidationContext.java
  src/main/java/indipage/org/indipage/external/client/aws/S3Service.java
  src/main/resources/application.yaml
Labels: REFACTOR, 🐭 승희

#118 [ADD] 로그인 & 회원가입 로직 완성
  src/main/java/indipage/org/indipage/api/article/controller/ArticleController.java
  src/main/java/indipage/org/indipage/api/auth/controller/AuthController.java
  src/main/java/indipage/org/indipage/api/auth/dto/request/LoginRequestDto.java
  src/main/java/indipage/org/indipage/api/auth/dto/response/LoginResponseDto.java
  src/main/java/indipage/org/indipage/api/bookmark/controller/BookmarkController.java
  src/main/java/indipage/org/indipage/api/space/controller/SpaceController.java
  src/main/java/indipage/org/indipage/api/user/controller/UserController.java
  src/main/java/indipage/org/indipage/api/user/service/UserService.java
  src/main/java/indipage/org/indipage/auth/JwtProvider.java
  src/main/java/indipage/org/indipage/auth/dto/OAuthUserResponseDto.java
  src/main/java/indipage/org/indipage/auth/service/AuthService.java
  src/main/java/indipage/org/indipage/auth/service/JWKs.java
  src/main/java/indipage/org/indipage/auth/service/OAuthClientProvider.java
  src/main/java/indipage/org/indipage/auth/service/google/GoogleOAuthClient.java
  src/main/java/indipage/org/indipage/config/WebConfig.java
  src/main/java/indipage/org/indipage/config/resolver/UserIdResolver.java
  src/main/java/indipage/org/indipage/domain/User.java
  src/main/java/indipage/org/indipage/domain/UserRepository.java
Labels: ADD

#120 [FIX] 애플 로그인 시 유효성 검사에서 필요하지 않은 로직을 삭제한다.
  src/main/java/indipage/org/indipage/auth/service/apple/AppleIdentityTokenProcessor.java
  src/main/java/indipage/org/indipage/auth/service/apple/AppleOAuthClient.java
Labels: FIX, 🐭 승희
